name: local action

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: npm ci
      shell: bash
      run: npm ci
