name: local action

runs:
  using: "composite"

  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: us-east-1
    DEPLOYMENT_ACCOUNT: ${{ secrets.DEV_ACCOUNT_ID }}

  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: npm ci
      shell: bash
      run: npm ci

