name: deploy dev2

on:
  push:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      DEPLOYMENT_ACCOUNT: ${{ secrets.DEV_ACCOUNT_ID }}

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/action
      - name: deploy to dev
        run: |
          npm run deploy:dev
