name: deploy dev

on:
  push:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      DEPLOYMENT_ACCOUNT: ${{ secrets.DEV_ACCOUNT_ID }}

    steps:
      - uses: actions/checkout@v2.3.4 # Necessary to access local action
      - name: Local Action Call
      id: local-action
      uses: ./.github/local-actions/action
      - name: deploy to dev
        run: |
          npm run deploy:dev
