name: deploy dev2

on:
  push:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/local-actions/action-dir
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEPLOYMENT_ACCOUNT: ${{ secrets.DEV_ACCOUNT_ID }}
      - name: deploy to dev
        run: |
          npm run deploy:dev
